[package]
name = "actix-mqtt"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "MQTT v3.1.1 Client/Server framework"
documentation = "https://docs.rs/actix-mqtt"
repository = "https://github.com/actix/actix-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
mqtt-codec = "0.3.0"
actix-codec = "0.2.0-alpha.1"
actix-service = "1.0.0-alpha.1"
actix-utils = "0.5.0-alpha.1"
actix-router = "0.1.5"
actix-server-config = "0.3.0-alpha.1"
actix-ioframe = "0.3.0-alpha.1"
actix-rt = "1.0.0-alpha.1"

derive_more = "0.15.0"
bytes = "0.4"
either = "1.5.2"
futures = "0.3.1"
pin-project = "0.4.6"
log = "0.4"
string = "0.2.0"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6"
actix-connect = "1.0.0-alpha.1"
actix-server = "0.8.0-alpha.1"
actix-testing = "0.3.0-alpha.1"
tokio-net = "0.2.0-alpha.6"

[patch.crates-io]
actix-mqtt = { path = "." }
mqtt-codec = { path = "codec" }
