[package]
name = "actix-mqtt"
version = "0.1.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "MQTT v3.1.1 Client/Server framework"
documentation = "https://docs.rs/actix-mqtt"
repository = "https://github.com/actix/actix-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
mqtt-codec = "0.2.0"
actix-codec = "*"
actix-service = "*"
actix-utils = "*"
actix-router = "*"
actix-server-config = "*"
actix-ioframe = "*"

derive_more = "0.15.0"
bytes = "0.4"
either = "1.5.2"
futures = "0.1.25"
log = "0.4"
string = "0.2.0"
serde = "1.0"
serde_json = "1.0"
tokio-current-thread = "0.1.4"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6"
actix-connect = "0.2.0"
actix-server = "0.6.1"
actix-testing = "0.1.0"
tokio-tcp = "0.1"

[patch.crates-io]
actix-mqtt = { path = "." }
mqtt-codec = { path = "codec" }
